export const SET_NAVIGATION_LINKS = 'SET_NAVIGATION_LINKS';

export const CONTACT_REQUEST_SAVED = 'CONTACT_REQUEST_SAVED';
export const ADD_REGISTERED_CARER = 'ADD_REGISTERED_CARER';

export const ADD_CARERS = 'ADD_CARERS';
export const SET_SELECTED_CARER = 'SET_SELECTED_CARER';

export const AVATAR_SELECTED = 'AVATAR_SELECTED';
export const AVATAR_UPLOAD_ERROR = 'AVATAR_UPLOAD_ERROR';
export const CLEAR_UPLOAD_ERROR = 'CLEAR_UPLOAD_ERROR';