export const GET_NAVIGATION_LINKS = 'GET_NAVIGATION_LINKS';

export const CONTACT_REQUEST_SAVED = 'CONTACT_REQUEST_SAVED';
export const CARER_REGISTERED = 'CARER_REGISTERED';

export const ADD_CARERS = 'ADD_CARERS';
export const SET_SELECTED_CARER = 'SET_SELECTED_CARER';

export const AVATAR_SELECTED = 'AVATAR_SELECTED';